name = "Etch Lite"
license = "MIT"
licenselink = "https://github.com/LukasJoswiak/etch/blob/master/LICENSE"
description = "Ultra-light Hugo theme focused on minimal page size"
homepage = "https://github.com/LukasJoswiak/etch"
demosite = "https://lukasjoswiak.github.io/etch/"
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "privacy", "lightweight"]
features = ["fast", "blog"]
min_version = "0.41"

[author]
  name = "Lukas Joswiak"
  homepage = "https://lukasjoswiak.com"
